name: Export Branding Assets

on:
  push:
    branches: [ main, master ]
    paths:
      - 'branding/**.svg'
      - 'branding/export.sh'
  workflow_dispatch: {}

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Inkscape
        run: |
          sudo apt-get update
          sudo apt-get install -y inkscape

      - name: Export PNGs
        run: |
          cd branding
          chmod +x export.sh
          ./export.sh

      - name: Upload PNG artifacts
        uses: actions/upload-artifact@v4
        with:
          name: branding-pngs
          path: branding/png/
